version: '3'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: drontaxi
      POSTGRES_PASSWORD: drontaxi
    ports:
      - 5432:5432
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db